### PR TITLE
jQuery free footnotes

### PR DESCRIPTION
**Pull request by servicethinker**
Found this script: http://www.cssscript.com/smooth-scroll-to-animation-with-anchor-scrolling-js-library/
... and changed and minimized it to use it with footnotes.

The code is licensed under the MIT license and works with typical browsers, but haven't been tested it with IE.

### CODE REVIEW

**Comment by distantnative** [comment]
I get the following error:
```
SyntaxError: Unexpected token '&'
```

That said, I realized that my old smooth scrolling seems to be broken as well.

**Comment by distantnative** [comment]
I think I found the problem (tho not yet the solution):

Since the script part is added with the footnotes list at the end of the text field, it also gets the whole Kirbytext treatment. Therefore, characters like `>` get changed to `&gt;` :(

**Comment by distantnative** [comment]
Transformed it to:

```
return "<script>document.addEventListener('DOMContentLoaded',function(){'use strict';for(var e=document.querySelectorAll('.footnote \> a[href\*='#']:not([href='#']), .footnotereverse \> a[href\*='#']:not([href='#'])),t=e.length,n=/firefox|trident/i.test(navigator.userAgent)?document.documentElement:document.body,o=function(e,t,n,o){return(e/=o/2)\<1?n/2\*e\*e\*e+t:n/2\*((e-=2)\*e\*e+2)+t};t--;)e.item(t).addEventListener('click',function(e){var t,r=n.scrollTop,i=document.getElementById(/[^#]+$/.exec(this.href)[0]).getBoundingClientRect().top-".c::get('footnotes.offset', 0).",c=n.scrollHeight-window.innerHeight,u=c\>r+i?i:c-r,d=900,a=function(e){t=t||e;var i=e-t,c=o(i,r,u,d);n.scrollTop=c,d\>i\&\&requestAnimationFrame(a)};requestAnimationFrame(a),e.preventDefault()})});</script>";
```

Still, I cannot get to escape the ampersands `&` in `n.scrollTop=c,d\>i\&\&requestAnimationFrame(a)`(near the end) correctly. Keeps converting them to `&amp;`.

And I get the error 
```
SyntaxError: Invalid character: '#'
```

**Comment by servicethinker** [comment]
I don't get the syntax error in Safari, Chrome, Opera or Firefox. Which browser and which version do you use?

 I also can't explain it, because everything in the string should be automatically escaped by php. So I think it has to be a javascript syntax error - but I don't get one.

By the way: Your transformed version couldn't work, because browsers seems to need `"` to select DOM elements correctly (yes I know - normally not). I've tested the script, `a[href*='#']:not([href='#']` doesn't worked but `a[href*="#"]:not([href="#"]` does.

Anyway. I cleaned up the code a bit and inserted the non-minified source code for better debugging.

**Comment by distantnative** [comment]
How do you echo the "footnoted" text field in PHP?

**Comment by servicethinker** [comment]
Simply with `<?php echo $page->text()->kirbytext(); ?>` (also tried with `<?php echo kirbytext($page->text()); ?>` - both works). Have you checked it by deleting all cache files and your browser cache first?

**Comment by distantnative** [comment]
Working now! Don't know why not before. I'll prob set the duration to 700 and will include this in the next release (prob tomorrow, I'll clode the PR cause I'll commit it to the dev branch). THANKS a lot!

**Pull request closed without merging**
